/*
 * emit_header.c - Generate .h and .c output files
 *
 * Generates:
 *   zx0em_blob_data.h  - compressed blob array + size constants
 *   zx0em_blob_data.c  - compressed blob data
 *   zx0em_index.h      - asset index (enum, entry table, types)
 *   zx0em_runtime.h    - standalone runtime API (header-only)
 */

#include "zx0em_blob.h"
#include "png_decode.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

static const char *type_name(int t) {
    switch (t) {
        case ZX0EM_TYPE_IMAGE:       return "IMAGE";
        case ZX0EM_TYPE_TEXT_RAW:    return "TEXT_RAW";
        case ZX0EM_TYPE_TEXT_BPE:    return "TEXT_BPE";
        case ZX0EM_TYPE_FONT:        return "FONT";
        case ZX0EM_TYPE_BINARY:      return "BINARY";
        default: return "UNKNOWN";
    }
}

int zx0em_emit_header(zx0em_ctx_t *ctx, const char *out_dir) {
    char path[1024];

    /* ------------------------------------------------------------ */
    /* 1. zx0em_blob_data.h                                         */
    /* ------------------------------------------------------------ */
    snprintf(path, sizeof(path), "%s/zx0em_blob_data.h", out_dir);
    FILE *f = fopen(path, "w");
    if (!f) { perror(path); return -1; }

    fprintf(f, "/* Auto-generated by zx0em_pack. Do not edit. */\n");
    fprintf(f, "#ifndef ZX0EM_BLOB_DATA_H\n");
    fprintf(f, "#define ZX0EM_BLOB_DATA_H\n\n");
    fprintf(f, "#define ZX0EM_UNCOMPRESSED_SIZE %zuU\n", ctx->blob_size);
    fprintf(f, "#define ZX0EM_COMPRESSED_SIZE   %zuU\n\n", ctx->compressed_size);
    fprintf(f, "extern const unsigned char zx0em_blob_z[ZX0EM_COMPRESSED_SIZE];\n\n");
    fprintf(f, "#endif /* ZX0EM_BLOB_DATA_H */\n");
    fclose(f);

    /* ------------------------------------------------------------ */
    /* 2. zx0em_blob_data.c                                         */
    /* ------------------------------------------------------------ */
    snprintf(path, sizeof(path), "%s/zx0em_blob_data.c", out_dir);
    f = fopen(path, "w");
    if (!f) { perror(path); return -1; }

    fprintf(f, "/* Auto-generated by zx0em_pack. Do not edit. */\n");
    fprintf(f, "#include \"zx0em_blob_data.h\"\n\n");
    fprintf(f, "const unsigned char zx0em_blob_z[ZX0EM_COMPRESSED_SIZE] = {\n");
    for (size_t i = 0; i < ctx->compressed_size; i++) {
        if ((i % 16) == 0) fprintf(f, "    ");
        fprintf(f, "0x%02x,", ctx->compressed[i]);
        if ((i % 16) == 15 || i == ctx->compressed_size - 1) fprintf(f, "\n");
    }
    fprintf(f, "};\n");
    fclose(f);

    /* ------------------------------------------------------------ */
    /* 3. zx0em_index.h                                             */
    /* ------------------------------------------------------------ */
    unsigned int max_scratch = 0;
    for (int i = 0; i < ctx->asset_count; i++) {
        zx0em_asset_t *a = &ctx->assets[i];
        if (a->asset_type == ZX0EM_TYPE_IMAGE) {
            unsigned int scratch = 0;
            int sf = a->filters & 0x0F;
            if (sf == 5 || (sf >= 11 && sf <= 13)) { /* PLANAR GRAY_ALPHA (standalone or chained) */
                scratch = (unsigned int)(a->data_size / 2);
            } else if (sf == 6 || (sf >= 14 && sf <= 16)) { /* PLANAR RGBA (standalone or chained) */
                scratch = (unsigned int)((a->data_size / 4) * 3);
            }
            if (scratch > max_scratch) max_scratch = scratch;
        }
    }

    snprintf(path, sizeof(path), "%s/zx0em_index.h", out_dir);
    f = fopen(path, "w");
    if (!f) { perror(path); return -1; }

    fprintf(f, "/* Auto-generated by zx0em_pack. Do not edit. */\n");
    fprintf(f, "#ifndef ZX0EM_INDEX_H\n");
    fprintf(f, "#define ZX0EM_INDEX_H\n\n");
    fprintf(f, "#include <stdint.h>\n\n");
    fprintf(f, "#define ZX0EM_MAX_PLANAR_SCRATCH_SIZE %u\n\n", max_scratch);

    /* Type constants */
    fprintf(f, "/* Asset types */\n");
    fprintf(f, "/* Asset types */\n");
    fprintf(f, "#define ZX0EM_TYPE_IMAGE        0\n");
    fprintf(f, "#define ZX0EM_TYPE_TEXT_RAW     4\n");
    fprintf(f, "#define ZX0EM_TYPE_TEXT_BPE     5\n");
    fprintf(f, "#define ZX0EM_TYPE_FONT         6\n");
    fprintf(f, "#define ZX0EM_TYPE_BINARY       7\n\n");

    /* Pixel format constants */
    fprintf(f, "/* Pixel formats */\n");
    fprintf(f, "#define ZX0EM_PIXFMT_GRAY_ALPHA 0\n");
    fprintf(f, "#define ZX0EM_PIXFMT_PALETTE    1\n");
    fprintf(f, "#define ZX0EM_PIXFMT_RGBA       2\n");
    fprintf(f, "#define ZX0EM_PIXFMT_1BIT       3\n");
    fprintf(f, "#define ZX0EM_PIXFMT_NONE       7\n\n");

    /* Entry structure */
    fprintf(f, "typedef struct {\n");
    fprintf(f, "    const char *name;\n");
    fprintf(f, "    uint32_t    offset;\n");
    fprintf(f, "    uint32_t    size;\n");
    fprintf(f, "    uint16_t    width;\n");
    fprintf(f, "    uint16_t    height;\n");
    fprintf(f, "    uint8_t     type;      /* ZX0EM_TYPE_* */\n");
    fprintf(f, "    uint8_t     pixfmt;    /* ZX0EM_PIXFMT_* */\n");
    fprintf(f, "    uint8_t     palette_count;\n");
    fprintf(f, "    uint8_t     filters;   /* ZX0EM_FILTER_* */\n");
    fprintf(f, "    uint16_t    parent_id; /* MST parent index (0xFFFF if none) */\n");
    fprintf(f, "} zx0em_entry_t;\n\n");

    /* Enum */
    fprintf(f, "#define ZX0EM_ENTRY_COUNT %d\n\n", ctx->asset_count);
    fprintf(f, "enum {\n");
    for (int i = 0; i < ctx->asset_count; i++) {
        fprintf(f, "    ZX0EM_%s = %d,\n", ctx->assets[i].macro, i);
    }
    fprintf(f, "    ZX0EM__COUNT = %d\n", ctx->asset_count);
    fprintf(f, "};\n\n");

    /* Entry table */
    fprintf(f, "static const zx0em_entry_t zx0em_entries[ZX0EM_ENTRY_COUNT] = {\n");
    for (int i = 0; i < ctx->asset_count; i++) {
        zx0em_asset_t *a = &ctx->assets[i];
        /* Calculate stored size (including palette if any) */
        size_t stored_size = a->data_size;
        if (a->pixfmt == ZX0EM_PIXFMT_PALETTE && a->palette_count > 0) {
            stored_size += 1 + (size_t)(a->palette_count) * 4;
        }
        fprintf(f, "    { \"%s\", %uU, %zuU, %u, %u, "
                   "ZX0EM_TYPE_%s, ZX0EM_PIXFMT_%s, %u, 0x%02X, 0x%04X },\n",
                a->name,
                a->blob_offset,
                stored_size,
                (unsigned)a->width,
                (unsigned)a->height,
                type_name(a->asset_type),
                zx0em_pixfmt_name(a->pixfmt),
                (unsigned)a->palette_count,
                (unsigned)a->filters,
                (unsigned)a->parent_id);
    }
    fprintf(f, "};\n\n");

    /* Per-asset offset/size macros for direct access */
    fprintf(f, "/* Direct access macros */\n");
    for (int i = 0; i < ctx->asset_count; i++) {
        zx0em_asset_t *a = &ctx->assets[i];
        size_t stored_size = a->data_size;
        if (a->pixfmt == ZX0EM_PIXFMT_PALETTE && a->palette_count > 0)
            stored_size += 1 + (size_t)(a->palette_count) * 4;
        fprintf(f, "#define ZX0EM_%s_OFFSET %uU\n", a->macro, a->blob_offset);
        fprintf(f, "#define ZX0EM_%s_SIZE   %zuU\n", a->macro, stored_size);
        if (a->width > 0) {
            fprintf(f, "#define ZX0EM_%s_W      %u\n", a->macro, (unsigned)a->width);
            fprintf(f, "#define ZX0EM_%s_H      %u\n", a->macro, (unsigned)a->height);
        }
        fprintf(f, "\n");
    }

    fprintf(f, "#endif /* ZX0EM_INDEX_H */\n");
    fclose(f);

    /* ------------------------------------------------------------ */
    /* 4. zx0em_runtime.h                                           */
    /* ------------------------------------------------------------ */
    snprintf(path, sizeof(path), "%s/zx0em_runtime.h", out_dir);
    f = fopen(path, "w");
    if (!f) { perror(path); return -1; }

    fprintf(f,
        "/* Auto-generated by zx0em_pack. Do not edit. */\n"
        "/*\n"
        " * zx0em_runtime.h - Standalone runtime API for embedded assets\n"
        " *\n"
        " * No dependency on libpng, tqt3, or any framework.\n"
        " * Images are raw pixels ready for direct use.\n"
        " * Include this header + zx0em_blob_data.c in your project.\n"
        " * You also need the ZX0 decompressor (~95 lines of C).\n"
        " */\n"
        "#ifndef ZX0EM_RUNTIME_H\n"
        "#define ZX0EM_RUNTIME_H\n\n"
        "#include \"zx0em_index.h\"\n"
        "#include \"zx0em_blob_data.h\"\n\n"
        "#ifdef __cplusplus\n"
        "extern \"C\" {\n"
        "#endif\n\n"
        "/* ZX0 decompressor (include zx0_decompress.c in your build) */\n"
        "int zx0_decompress_to(const unsigned char *in, int in_size,\n"
        "                      unsigned char *out, int out_max);\n\n"
        "static unsigned char zx0em_buf_[ZX0EM_UNCOMPRESSED_SIZE];\n"
        "static int zx0em_inited_ = 0;\n\n"
        "#if ZX0EM_MAX_PLANAR_SCRATCH_SIZE > 0\n"
        "static unsigned char _zx0em_planar_scratch[ZX0EM_MAX_PLANAR_SCRATCH_SIZE];\n"
        "#endif\n\n"
        "static inline unsigned char paeth_predict(unsigned char a, unsigned char b, unsigned char c) {\n"
        "    int p = (int)a + (int)b - (int)c;\n"
        "    int pa = p > (int)a ? p - (int)a : (int)a - p;\n"
        "    int pb = p > (int)b ? p - (int)b : (int)b - p;\n"
        "    int pc = p > (int)c ? p - (int)c : (int)c - p;\n"
        "    if (pa <= pb && pa <= pc) return a;\n"
        "    if (pb <= pc) return b;\n"
        "    return c;\n"
        "}\n\n"
        "/* Initialize: decompress the blob. Call once at startup.\n"
        " * Returns 1 on success, 0 on failure. */\n"
        "static inline int zx0em_init(void) {\n"
        "    if (zx0em_inited_) return 1;\n"
        "    int n = zx0_decompress_to(zx0em_blob_z, (int)ZX0EM_COMPRESSED_SIZE,\n"
        "                              zx0em_buf_, (int)ZX0EM_UNCOMPRESSED_SIZE);\n"
        "    if (n != (int)ZX0EM_UNCOMPRESSED_SIZE) return 0;\n"
        "    /* Undo DELTA / XOR in-place */\n"
        "    for (int i = 0; i < ZX0EM_ENTRY_COUNT; i++) {\n"
        "        const zx0em_entry_t *e = &zx0em_entries[i];\n"
        "        if (e->type != ZX0EM_TYPE_IMAGE || e->filters == 0) continue;\n"
        "        int bpp = 1;\n"
        "        if (e->pixfmt == ZX0EM_PIXFMT_GRAY_ALPHA) bpp = 2;\n"
        "        else if (e->pixfmt == ZX0EM_PIXFMT_RGBA) bpp = 4;\n"
        "        unsigned int pitch = 0;\n"
        "        if (e->pixfmt == ZX0EM_PIXFMT_RGBA) pitch = (unsigned int)e->width * 4;\n"
        "        else if (e->pixfmt == ZX0EM_PIXFMT_GRAY_ALPHA) pitch = (unsigned int)e->width * 2;\n"
        "        else if (e->pixfmt == ZX0EM_PIXFMT_PALETTE) pitch = (unsigned int)e->width * 1;\n"
        "        else if (e->pixfmt == ZX0EM_PIXFMT_1BIT) pitch = ((unsigned int)e->width + 7) / 8;\n"
        "        unsigned int pal_size = 0;\n"
        "        if (e->pixfmt == ZX0EM_PIXFMT_PALETTE && e->palette_count > 0)\n"
        "            pal_size = 1 + (unsigned int)e->palette_count * 4;\n"
        "        unsigned char *data = &zx0em_buf_[e->offset + pal_size];\n"
        "        unsigned int size = e->size - pal_size;\n"
        "        unsigned char spatial = e->filters & 0x0F;\n"
        "        unsigned char inter   = e->filters & 0xF0;\n"
        "        /* 1. Reverse Spatial Filter */\n"
        "        if (spatial == 1) { /* LEFT XOR */\n"
        "            for (unsigned int k = (unsigned int)bpp; k < size; k++) data[k] ^= data[k - bpp];\n"
        "        } else if (spatial == 2) { /* LEFT SUB */\n"
        "            for (unsigned int k = (unsigned int)bpp; k < size; k++) data[k] = (unsigned char)(data[k] + data[k - bpp]);\n"
        "        } else if (spatial == 3) { /* UP XOR */\n"
        "            for (unsigned int k = pitch; k < size; k++) data[k] ^= data[k - pitch];\n"
        "        } else if (spatial == 4) { /* UP SUB */\n"
        "            for (unsigned int k = pitch; k < size; k++) data[k] = (unsigned char)(data[k] + data[k - pitch]);\n"
        "        } else if (spatial == 5) { /* PLANAR (GRAY_ALPHA: GGG..AAA.. -> GAGAGA) */\n"
        "            unsigned int half = size / 2;\n"
        "            /* Save alpha channel (second half) */\n"
        "            for (unsigned int k = 0; k < half; k++)\n"
        "                _zx0em_planar_scratch[k] = data[half + k];\n"
        "            /* Spread gray values backward: pos i -> pos 2*i */\n"
        "            for (int k = (int)half - 1; k >= 1; k--)\n"
        "                data[k * 2] = data[k];\n"
        "            /* Interleave alpha from scratch */\n"
        "            for (unsigned int k = 0; k < half; k++)\n"
        "                data[k * 2 + 1] = _zx0em_planar_scratch[k];\n"
        "        } else if (spatial == 6) { /* PLANAR RGBA (RRR...GGG...BBB...AAA... -> RGBA RGBA...) */\n"
        "            unsigned int plane_sz = size / 4;\n"
        "            /* Save G, B, A channels in scratch */\n"
        "            for (unsigned int k = 0; k < plane_sz * 3; k++)\n"
        "                _zx0em_planar_scratch[k] = data[plane_sz + k];\n"
        "            /* Spread R values backward: pos i -> pos 4*i */\n"
        "            for (int k = (int)plane_sz - 1; k >= 0; k--)\n"
        "                data[k * 4] = data[k];\n"
        "            /* Interleave G, B, A from scratch */\n"
        "            for (unsigned int k = 0; k < plane_sz; k++) {\n"
        "                data[k * 4 + 1] = _zx0em_planar_scratch[k];\n"
        "                data[k * 4 + 2] = _zx0em_planar_scratch[plane_sz + k];\n"
        "                data[k * 4 + 3] = _zx0em_planar_scratch[plane_sz * 2 + k];\n"
        "            }\n"
        "        } else if (spatial == 7) { /* AVG XOR */\n"
        "            unsigned int px = 0, chan = 0;\n"
        "            for (unsigned int k = 0; k < size; k++) {\n"
        "                unsigned char left = (px > 0) ? data[k - bpp] : 0;\n"
        "                unsigned char up = (k >= pitch) ? data[k - pitch] : 0;\n"
        "                data[k] ^= (unsigned char)(((int)left + (int)up) / 2);\n"
        "                chan++; if (chan == (unsigned int)bpp) { chan = 0; px++; if (px == e->width) px = 0; }\n"
        "            }\n"
        "        } else if (spatial == 8) { /* AVG SUB */\n"
        "            unsigned int px = 0, chan = 0;\n"
        "            for (unsigned int k = 0; k < size; k++) {\n"
        "                unsigned char left = (px > 0) ? data[k - bpp] : 0;\n"
        "                unsigned char up = (k >= pitch) ? data[k - pitch] : 0;\n"
        "                data[k] = (unsigned char)(data[k] + (((int)left + (int)up) / 2));\n"
        "                chan++; if (chan == (unsigned int)bpp) { chan = 0; px++; if (px == e->width) px = 0; }\n"
        "            }\n"
        "        } else if (spatial == 9) { /* PAETH XOR */\n"
        "            unsigned int px = 0, chan = 0;\n"
        "            for (unsigned int k = 0; k < size; k++) {\n"
        "                unsigned char left = (px > 0) ? data[k - bpp] : 0;\n"
        "                unsigned char up = (k >= pitch) ? data[k - pitch] : 0;\n"
        "                unsigned char left_up = (px > 0 && k >= pitch) ? data[k - pitch - bpp] : 0;\n"
        "                data[k] ^= paeth_predict(left, up, left_up);\n"
        "                chan++; if (chan == (unsigned int)bpp) { chan = 0; px++; if (px == e->width) px = 0; }\n"
        "            }\n"
        "        } else if (spatial == 10) { /* PAETH SUB */\n"
        "            unsigned int px = 0, chan = 0;\n"
        "            for (unsigned int k = 0; k < size; k++) {\n"
        "                unsigned char left = (px > 0) ? data[k - bpp] : 0;\n"
        "                unsigned char up = (k >= pitch) ? data[k - pitch] : 0;\n"
        "                unsigned char left_up = (px > 0 && k >= pitch) ? data[k - pitch - bpp] : 0;\n"
        "                data[k] = (unsigned char)(data[k] + paeth_predict(left, up, left_up));\n"
        "                chan++; if (chan == (unsigned int)bpp) { chan = 0; px++; if (px == e->width) px = 0; }\n"
        "            }\n"
        "        } else if (spatial >= 11 && spatial <= 16) { /* CHAINED: secondary spatial + PLANAR */\n"
        "            /* Step 1: Undo secondary spatial filter (bpp=1, planar pitch=width) */\n"
        "            unsigned int pl_pitch = e->width;\n"
        "            int sec = 0;\n"
        "            if (spatial == 11 || spatial == 14) sec = 1;  /* LEFT_XOR */\n"
        "            else if (spatial == 12 || spatial == 15) sec = 3; /* UP_XOR */\n"
        "            else if (spatial == 13 || spatial == 16) sec = 10; /* PAETH_SUB */\n"
        "            if (sec == 1) {\n"
        "                for (unsigned int k = 1; k < size; k++) data[k] ^= data[k - 1];\n"
        "            } else if (sec == 3) {\n"
        "                for (unsigned int k = pl_pitch; k < size; k++) data[k] ^= data[k - pl_pitch];\n"
        "            } else if (sec == 10) {\n"
        "                unsigned int px2 = 0, chan2 = 0;\n"
        "                for (unsigned int k = 0; k < size; k++) {\n"
        "                    unsigned char left = (px2 > 0) ? data[k - 1] : 0;\n"
        "                    unsigned char up = (k >= pl_pitch) ? data[k - pl_pitch] : 0;\n"
        "                    unsigned char left_up = (px2 > 0 && k >= pl_pitch) ? data[k - pl_pitch - 1] : 0;\n"
        "                    data[k] = (unsigned char)(data[k] + paeth_predict(left, up, left_up));\n"
        "                    chan2++; if (chan2 == 1) { chan2 = 0; px2++; if (px2 == e->width) px2 = 0; }\n"
        "                }\n"
        "            }\n"
        "            /* Step 2: Undo PLANAR de-interleave */\n"
        "            if (spatial <= 13) { /* PLANAR GA */\n"
        "                unsigned int half = size / 2;\n"
        "                for (unsigned int k = 0; k < half; k++)\n"
        "                    _zx0em_planar_scratch[k] = data[half + k];\n"
        "                for (int k = (int)half - 1; k >= 1; k--)\n"
        "                    data[k * 2] = data[k];\n"
        "                for (unsigned int k = 0; k < half; k++)\n"
        "                    data[k * 2 + 1] = _zx0em_planar_scratch[k];\n"
        "            } else { /* PLANAR RGBA */\n"
        "                unsigned int plane_sz = size / 4;\n"
        "                for (unsigned int k = 0; k < plane_sz * 3; k++)\n"
        "                    _zx0em_planar_scratch[k] = data[plane_sz + k];\n"
        "                for (int k = (int)plane_sz - 1; k >= 0; k--)\n"
        "                    data[k * 4] = data[k];\n"
        "                for (unsigned int k = 0; k < plane_sz; k++) {\n"
        "                    data[k * 4 + 1] = _zx0em_planar_scratch[k];\n"
        "                    data[k * 4 + 2] = _zx0em_planar_scratch[plane_sz + k];\n"
        "                    data[k * 4 + 3] = _zx0em_planar_scratch[plane_sz * 2 + k];\n"
        "                }\n"
        "            }\n"
        "        }\n"
        "        /* 2. Reverse Inter-image Filter */\n"
        "        if (inter != 0 && e->parent_id != 0xFFFF) {\n"
        "            const zx0em_entry_t *parent = &zx0em_entries[e->parent_id];\n"
        "            unsigned int p_pal_size = 0;\n"
        "            if (parent->pixfmt == ZX0EM_PIXFMT_PALETTE && parent->palette_count > 0)\n"
        "                p_pal_size = 1 + (unsigned int)parent->palette_count * 4;\n"
        "            unsigned char *parent_data = &zx0em_buf_[parent->offset + p_pal_size];\n"
        "            if (inter == 0x10) { /* INTER XOR */\n"
        "                for (unsigned int k = 0; k < size; k++) data[k] ^= parent_data[k];\n"
        "            } else if (inter == 0x20) { /* INTER SUB */\n"
        "                for (unsigned int k = 0; k < size; k++) data[k] = (unsigned char)(data[k] + parent_data[k]);\n"
        "            }\n"
        "        }\n"
        "    }\n"
        "    zx0em_inited_ = 1;\n"
        "    return 1;\n"
        "}\n\n"
        "/* Get raw asset data by ID. Returns NULL on error.\n"
        " * Sets *size to the asset size in bytes. */\n"
        "static inline const unsigned char* zx0em_get(int id, unsigned int *size) {\n"
        "    if (!zx0em_inited_ || id < 0 || id >= ZX0EM_ENTRY_COUNT) return 0;\n"
        "    const zx0em_entry_t *e = &zx0em_entries[id];\n"
        "    if (size) *size = e->size;\n"
        "    return &zx0em_buf_[e->offset];\n"
        "}\n\n"
        "/* Get image asset with dimensions and pixel format.\n"
        " * Returns pointer to raw pixel data, or NULL. */\n"
        "static inline const unsigned char* zx0em_get_image(\n"
        "        int id, int *w, int *h, int *pixfmt) {\n"
        "    if (!zx0em_inited_ || id < 0 || id >= ZX0EM_ENTRY_COUNT) return 0;\n"
        "    const zx0em_entry_t *e = &zx0em_entries[id];\n"
        "    if (e->type != ZX0EM_TYPE_IMAGE) return 0; /* not an image */\n"
        "    if (w) *w = e->width;\n"
        "    if (h) *h = e->height;\n"
        "    if (pixfmt) *pixfmt = e->pixfmt;\n"
        "    return &zx0em_buf_[e->offset];\n"
        "}\n\n"
        "/* Get text asset. Returns pointer to text data, or NULL. */\n"
        "static inline const unsigned char* zx0em_get_text(\n"
        "        int id, unsigned int *len) {\n"
        "    if (!zx0em_inited_ || id < 0 || id >= ZX0EM_ENTRY_COUNT) return 0;\n"
        "    const zx0em_entry_t *e = &zx0em_entries[id];\n"
        "    if (e->type != ZX0EM_TYPE_TEXT_RAW && e->type != ZX0EM_TYPE_TEXT_BPE)\n"
        "        return 0;\n"
        "    if (len) *len = e->size;\n"
        "    return &zx0em_buf_[e->offset];\n"
        "}\n\n"
        "/* Helper to recursively expand BPE tokens */\n"
        "static inline void _zx0em_bpe_expand(unsigned char c, const unsigned char *dict, int dict_count, char *out_buf, int *out_len, int max_len) {\n"
        "    if (*out_len >= max_len - 1) return;\n"
        "    int found = 0;\n"
        "    for (int j = 0; j < dict_count; j++) {\n"
        "        if (dict[j * 3] == c) {\n"
        "            _zx0em_bpe_expand(dict[j * 3 + 1], dict, dict_count, out_buf, out_len, max_len);\n"
        "            _zx0em_bpe_expand(dict[j * 3 + 2], dict, dict_count, out_buf, out_len, max_len);\n"
        "            found = 1;\n"
        "            break;\n"
        "        }\n"
        "    }\n"
        "    if (!found) {\n"
        "        out_buf[(*out_len)++] = (char)c;\n"
        "    }\n"
        "}\n\n"
        "/* Decode BPE text. Requires user-provided buffer. */\n"
        "static inline int zx0em_decode_bpe(int id, char *out_buf, int max_len) {\n"
        "    if (!zx0em_inited_ || id < 0 || id >= ZX0EM_ENTRY_COUNT) return -1;\n"
        "    const zx0em_entry_t *e = &zx0em_entries[id];\n"
        "    if (e->type != ZX0EM_TYPE_TEXT_BPE) {\n"
        "        /* Not BPE, just copy */\n"
        "        int cplen = e->size < (unsigned int)max_len ? (int)e->size : max_len - 1;\n"
        "        for (int i=0; i<cplen; i++) out_buf[i] = (char)zx0em_buf_[e->offset + i];\n"
        "        out_buf[cplen] = '\\0';\n"
        "        return cplen;\n"
        "    }\n"
        "    const unsigned char *p = &zx0em_buf_[e->offset];\n"
        "    int dict_count = *p++;\n"
        "    const unsigned char *dict = p;\n"
        "    p += dict_count * 3;\n"
        "    int in_len = e->size - 1 - dict_count * 3;\n"
        "    int out_len = 0;\n"
        "    for (int i = 0; i < in_len && out_len < max_len - 1; i++) {\n"
        "        _zx0em_bpe_expand(p[i], dict, dict_count, out_buf, &out_len, max_len);\n"
        "    }\n"
        "    out_buf[out_len] = '\\0';\n"
        "    return out_len;\n"
        "}\n\n"
        "/* Get asset name by ID */\n"
        "static inline const char* zx0em_name(int id) {\n"
        "    if (id < 0 || id >= ZX0EM_ENTRY_COUNT) return 0;\n"
        "    return zx0em_entries[id].name;\n"
        "}\n\n"
        "#ifdef __cplusplus\n"
        "}\n"
        "#endif\n\n"
        "#endif /* ZX0EM_RUNTIME_H */\n");
    fclose(f);

    if (ctx->verbose)
        printf("Generated: zx0em_blob_data.h, zx0em_blob_data.c, "
               "zx0em_index.h, zx0em_runtime.h\n");

    return 0;
}
